### ISSUE TITLE
Cannot connect the jesec/flood Server

### ISSUE THREAD

**Issue by GitHubGeek** [pt-plugins/PT-Plugin-Plus#715]
- PT Plugin Plus version: __1.5.1__
- PT Plugin Plus installation method: __Microsoft Edge Market__
- Browser name and version: __Edge Dev__
- Whether the browser has other plugins installed: __No Plugin__
- Is it working properly after disabling other plugins: __N/A__
- Problem Description:

My Flood instance is available on IPv6 address only. Example: `http://[fe80:1234::1]/my-flood-example/`

When I try to add it, the Test Connection would spin forever. The download button behaves the same - spinning forever.

**Comment by Rhilip** [comment]
It seems very strange, Since we don't set any restrictions on connect domain.

For your problem description, I guess you are use flood as rtorrent's WEB server, is it right?
However our realization of Flood is for legacy Flood ( aka Flood-UI/flood ) now , and Not compatible with [jesec/flood](https://github.com/jesec/flood) , so I think it's main reason you can't connect the flood server, but not the IPv6 address

**Comment by GitHubGeek** [comment]
Thank you so much for the quick response.

Indeed, I'm running jesec's flood fork. Any plan to support this fork?

**Comment by Rhilip** [comment]
That's over. Our realization of Flood was built on `Jul 11, 2019` and never update since then.
but jesec's flood fork is release on AUGUST 25, 2020 (from his first blog [here](https://flood.js.org/Changelog-3.0.0/))

However, jesec's folld fork is not compatible with legacy Flood, which you can see the discussion I opened at https://github.com/jesec/flood/discussions/149 . 
And at that moment, wo just want to support both Flood on our next major release ( see https://github.com/ronggang/PT-Plugin-Plus/blob/next/src/background/btclients/Flood.ts ) .

Now I will set this issue into Milestone `v1.5.2`, and work on it this days.

**Comment by GitHubGeek** [comment]
Greatly appreciate your help. Hope it will support jesec flood `master` branch.

**Comment by bingyupiaoyao** [comment]
still cannot connect to flood 4.7, any solution to that?

**Comment by bingyupiaoyao** [comment]
@ted423 能否修一下这个？现在还是连不上flood 4.7

**Comment by bingyupiaoyao** [comment]
@Rhilip still cannot connect to flood 4.7, any solution to that?
